Repository docker/swarmkit, pull requests merged in 2018-04, with the labels that each got.

#2584 [backport 17.06]Adding logic to restore networks in order
  manager/allocator/allocator_test.go
  manager/allocator/network.go
Labels: area/networking

#2551 RoleManager will remove deleted nodes from the cluster membership
  manager/role_manager.go
  manager/role_manager_test.go
Labels: area/raft

#2557 Task reaper should delete tasks with removed slots that were not yet assigned
  manager/orchestrator/taskreaper/task_reaper.go
  manager/orchestrator/taskreaper/task_reaper_test.go
Labels: area/orchestration
